[[headers]]
  for = "/*.js"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[headers]]
  for = "/fonts/*"
  [headers.values]
	cache-control = '''
	public,
	max-age=31536000,
	immutable'''

[[redirects]]
  from = "https://aggelosarvanitakis.me/*"
  to = "https://aggelos.dev/:splat"
  status = 301
  force = true
